import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";
import clsx from "clsx";

// import { ThemeProvider as NextThemesProvider } from "next-themes";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "white",
        },
      }}
    >
      <html lang="en">
        <body className={clsx(dmSans.className, "antialiased ")}>
          {/* <NextThemesProvider attribute="class" defaultTheme="dark"> */}
          {children}
          {/* </NextThemesProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
